### ISSUE TITLE
站点流量统计-js 

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [xgqfrms/cdn#13]
https://gist.github.com/xgqfrms-GitHub/6a16df85644b814265abe98150280d0f

**Comment by Dzy395** [comment]
你信我会拿着这些去报警还是通过第三方取证后找出你个人信息,把你调用模拟器黑钱的过程受害者让他们搞得你家破人亡？

**Comment by Dzy395** [comment]
你搞了我这么久了，至少也得给我个说法吧,你要觉得我真拿你没办法,ok.当我今天与你的对话是在放屁.

**Comment by Dzy395** [comment]
我的联系方式你太多了，微信还是电话你自己选吧,期待与你见面.
