### ISSUE TITLE
CND jquery lib 使用教程！

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [xgqfrms/cdn#5]
# master does not work!
url?raw=true 
### demo
[url?raw=true ](https://raw.githubusercontent.com/xgqfrms/cdn/master/jquery/jquery-3.1.0.min.js)
<script src="https://raw.githubusercontent.com/xgqfrms/cdn/master/jquery/jquery-3.1.0.min.js"></script>
***
***
# gh-pages does good work!
url
### demo
[CDN](https://xgqfrms.github.io/cdn/jquery/jquery-3.1.0.min.js)
<script src="https://xgqfrms.github.io/cdn/jquery/jquery-3.1.0.min.js"></script>

**Comment by xgqfrms** [comment]
good job!
